"use client";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, CircleStop, FileCheck2, Gauge, LockKeyhole, Radar, ShieldCheck, Sparkles, TimerReset } from "lucide-react";

const policies=["Kill switch","Simulated only","Evidence complete","Source verified","Fresh market data","BNBUSDT only","Ratio bounded","No over-hedge","Maximum 2×","Notional bounds","Funding limit","Plan unexpired","Single use"];
const stages=[{n:"01",title:"Inspect",copy:"Source-labelled BNB spot, perpetual, funding, contract rules, and portfolio evidence enter one normalized snapshot."},{n:"02",title:"Calculate",copy:"Decimal-safe sizing turns your requested protection into an exact short adjustment, margin requirement, and carrying-cost estimate."},{n:"03",title:"Gate",copy:"Thirteen deterministic checks run in stable order. Language can explain the decision; it cannot override policy."},{n:"04",title:"Confirm",copy:"You approve one exact plan ID before a short-lived, single-use nonce permits simulated execution."},{n:"05",title:"Prove",copy:"The opening position and reduce-only unwind produce linked canonical receipts with SHA-256 digests."}];

function Mark(){return <div className="mark" aria-hidden="true"><span/></div>}
export default function LandingPage(){return <main className="long-landing">
  <nav className="public-nav"><Link href="/" className="public-brand"><Mark/><span><strong>HedgeKnight</strong><small>by Umbra</small></span></Link><div><a href="#mechanism">How it works</a><a href="#safety">Safety</a><a href="#evidence">Evidence</a></div><Link className="nav-launch" href="/demo">Launch demo <ArrowRight/></Link></nav>
  <section className="hero-long"><div className="hero-copy"><div className="truth-tag"><span/> DEMO SYSTEM · SIMULATED EXECUTION</div><h1>Keep the asset.<br/><em>Cut the exposure.</em></h1><p>HedgeKnight turns a plain-language protection request into a calculated, risk-checked and monitored BNB hedge—without asking you to sell the underlying asset.</p><div className="hero-actions"><Link href="/demo">Run the 60-second demo <ArrowRight/></Link><a href="#mechanism">Trace the mechanism <ChevronDown/></a></div><div className="hero-facts"><span>No wallet</span><span>No funds</span><span>No live orders</span><span>Every assumption visible</span></div></div><div className="command-console"><div className="console-top"><span>PROTECTION REQUEST</span><span className="console-live">READY</span></div><blockquote>“I hold 10 BNB. Hedge 50% of my exposure for 24 hours.”</blockquote><div className="exposure-demo"><div className="measure-label"><span>NET EXPOSURE</span><strong>5.000 <small>BNB</small></strong></div><div className="measure-scale"><span>0</span><span>5</span><span>10 BNB</span></div><div className="measure-bar"><i/><b/></div><div className="measure-legend"><span><i/>5 BNB simulated short</span><span><i/>5 BNB retained exposure</span></div></div><div className="console-costs"><div><span>HEDGE NOTIONAL</span><strong>$3,059.50</strong></div><div><span>MARGIN · 2×</span><strong>$1,529.75</strong></div><div><span>EST. COST</span><strong>$3.37</strong></div></div><div className="console-pass"><ShieldCheck/> 13 deterministic checks passed <ArrowRight/></div></div></section>
  <section className="ticker"><span>BNB SPOT <strong>$612.40</strong></span><span>BNB PERPETUAL <strong>$611.90</strong></span><span>FUNDING / 8H <strong>0.0100%</strong></span><span>DATA SOURCE <strong>BINANCE PUBLIC REPLAY</strong></span><span>EXECUTION <strong>SIMULATED</strong></span></section>
  <section className="thesis" id="mechanism"><div className="section-lead"><h2>A hedge is not one click.<br/><span>It is a controlled sequence.</span></h2><p>Manual protection means calculation, contract rules, costs, margin, confirmation, monitoring, and a safe exit. HedgeKnight binds the whole job into one auditable agent operation.</p></div><div className="stage-list">{stages.map(s=><article key={s.n}><span>{s.n}</span><h3>{s.title}</h3><p>{s.copy}</p><ArrowRight/></article>)}</div></section>
  <section className="policy-section" id="safety"><div className="policy-copy"><div className="truth-tag"><span/> DETERMINISTIC AUTHORITY</div><h2>The model can interpret.<br/>It cannot bend the rules.</h2><p>Every plan passes through code-defined policy before confirmation and again before simulated execution. A blocked check explains what failed and how to correct it.</p><div className="blocked-sample"><CircleStop/><span><strong>LEVERAGE_LIMIT</strong><small>10× requested. Use 2× leverage or less.</small></span></div><Link href="/demo">Try all 10 judge scenarios <ArrowRight/></Link></div><div className="policy-matrix">{policies.map((p,i)=><div key={p}><span>{String(i+1).padStart(2,"0")}</span><strong>{p}</strong><Check/></div>)}</div></section>
  <section className="proof-section" id="evidence"><div className="receipt-visual"><div className="receipt-head"><FileCheck2/><span><strong>Opening complete</strong><small>OPENING</small></span></div><dl><div><dt>MODE</dt><dd>demo</dd></div><div><dt>EXECUTION</dt><dd>simulated</dd></div><div><dt>PLAN</dt><dd>9d2b03d0…</dd></div><div><dt>POSITION</dt><dd>5.000 BNB short</dd></div><div><dt>FINAL STATE</dt><dd className="ok">completed</dd></div></dl><div className="receipt-digest"><span>SHA-256</span><code>7fe343b10242ce63c0…</code><Check/></div></div><div className="proof-copy"><h2>Protection you can verify after the moment has passed.</h2><p>Opening and closing receipts preserve the request, normalized intent, evidence, calculations, ordered risk decisions, confirmation time, simulated position, and final state.</p><ul><li><LockKeyhole/>Canonical JSON excludes the digest field before hashing</li><li><TimerReset/>Closing receipts link back to the opening lifecycle</li><li><Radar/>Replay, connected data, and simulation remain distinct</li></ul></div></section>
  <section className="architecture"><h2>Two entry points.<br/>One source of truth.</h2><div className="arch-flow"><div><Sparkles/><strong>Public product demo</strong><small>Next.js dashboard · no login</small></div><span>REST / SSE</span><div className="arch-core"><ShieldCheck/><strong>Shared HedgeKnight engine</strong><small>Decimal math · policy · plans · receipts</small></div><span>MCP</span><div><Gauge/><strong>Binance Agent OS</strong><small>AI host coordinates source evidence</small></div></div><p>Official Binance MCP is the connected evidence boundary. HedgeKnight supplies the protection intelligence. All financial actions in this submission remain simulated.</p></section>
  <section className="final-cta"><div className="mark-large"><Mark/></div><h2>See 10 BNB become<br/><span>5 BNB of net exposure.</span></h2><p>No account. No typing required. The complete protection flow takes less than a minute.</p><Link href="/demo">Enter the HedgeKnight console <ArrowRight/></Link></section>
  <footer><div className="public-brand"><Mark/><span><strong>HedgeKnight</strong><small>by Umbra</small></span></div><p>Portfolio protection through Binance Agent OS.<br/>Demo execution only. No guarantee of profit or complete protection.</p><Link href="/demo">Launch demo <ArrowRight/></Link></footer>
 </main>}
