"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDownToLine, Check, ChevronRight, CircleStop, Clock3, Copy, FileCheck2, Gauge, LayoutDashboard, LockKeyhole, Menu, OctagonAlert, Power, Radar, ReceiptText, RefreshCw, Settings, ShieldCheck, Sparkles, X } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const commandDefault = "I hold 10 BNB. Hedge 50% of my exposure for 24 hours.";
type Any = Record<string, any>;
const money = (v:any) => `$${Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

async function call(path:string, init?:RequestInit) {
  const response = await fetch(`${API}${path}`, {headers:{"Content-Type":"application/json"},...init});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error?.message || "Request failed");
  return data;
}

function Mark(){return <div className="mark" aria-hidden="true"><span/></div>}
function Badge({children,tone="gold"}:{children:React.ReactNode,tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

export default function Dashboard(){
  const [nav,setNav]=useState("Overview"), [mobile,setMobile]=useState(false), [command,setCommand]=useState(commandDefault);
  const [ratio,setRatio]=useState(50), [duration,setDuration]=useState(24), [leverage,setLeverage]=useState(2);
  const [plan,setPlan]=useState<Any|null>(null), [position,setPosition]=useState<Any|null>(null), [receipts,setReceipts]=useState<Any[]>([]), [scenarios,setScenarios]=useState<Any[]>([]);
  const [busy,setBusy]=useState(""), [error,setError]=useState(""), [stage,setStage]=useState(0), [kill,setKill]=useState(false);
  const proposal=plan?.proposal, approved=plan?.risk?.decision==="approved";
  const hedge=position?.state==="open"?Number(position.hedge_ratio):0;
  const net=10-(position?.state==="open"?Number(position.remaining_quantity):0);
  const navItems=[{n:"Overview",i:LayoutDashboard},{n:"Create hedge",i:ShieldCheck},{n:"Monitor",i:Radar},{n:"Receipts",i:ReceiptText},{n:"Activity",i:Activity},{n:"Settings",i:Settings}];
  const activePanel=useMemo(()=> nav==="Overview"?"overview":nav==="Create hedge"?"create":nav.toLowerCase(),[nav]);
  const refresh=async()=>{const [s,p,r,sc]=await Promise.all([call("/api/status"),call("/api/positions/active"),call("/api/receipts"),call("/api/scenarios")]);setKill(s.kill_switch);setPosition(p);setReceipts(r);setScenarios(sc)};
  useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
  const propose=async()=>{setBusy("Calculating");setError("");setStage(0);try{const intent=await call("/api/intents/parse",{method:"POST",body:JSON.stringify({command})});intent.target_ratio=String(ratio);intent.duration_hours=duration;intent.leverage=leverage;intent.execution="simulated";const p=await call("/api/plans",{method:"POST",body:JSON.stringify(intent)});setPlan(p);setStage(4)}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const confirm=async()=>{if(!plan)return;setBusy("Confirming exact plan");try{const p=await call(`/api/plans/${plan.plan_id}/confirm`,{method:"POST",body:JSON.stringify({plan_id:plan.plan_id})});setPlan(p)}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const simulate=async()=>{if(!plan)return;setBusy("Simulating fill");setStage(5);try{const r=await call(`/api/plans/${plan.plan_id}/simulate`,{method:"POST"});setPosition(r.position);setReceipts(x=>[r.receipt,...x]);setPlan({...plan,state:"completed"});setStage(8);setNav("Monitor")}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const loadScenario=async(id:string)=>{setBusy("Loading scenario");setError("");try{const r=await call(`/api/scenarios/${id}/load`,{method:"POST"});setPlan(r.plan);setRatio(r.scenario.ratio);setDuration(r.scenario.duration);setLeverage(r.scenario.leverage);setKill(id==="kill-switch");setNav("Create hedge")}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const unwind=async()=>{if(!position)return;setBusy("Simulating reduce-only unwind");try{await call(`/api/positions/${position.position_id}/unwind-plan`,{method:"POST"});const r=await call(`/api/positions/${position.position_id}/unwind-simulate`,{method:"POST"});setPosition(r.position);setReceipts(x=>[r.receipt,...x])}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const toggleKill=async()=>{const s=await call("/api/settings/kill-switch",{method:"POST",body:JSON.stringify({enabled:!kill})});setKill(s.kill_switch)};
  return <div className="app-shell">
    <aside className={mobile?"open":""}>
      <div className="brand"><Mark/><div><strong>HedgeKnight</strong><span>by Umbra</span></div><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div>
      <nav aria-label="Primary">{navItems.map(({n,i:I})=><button key={n} className={nav===n?"active":""} onClick={()=>{setNav(n);setMobile(false)}}><I size={18}/><span>{n}</span>{nav===n&&<ChevronRight size={15}/>}</button>)}</nav>
      <div className="aside-foot"><div className="source-dot"><span/> Replay data</div><p>Public Binance market fixture<br/>08 Sep 2026 · 12:00 UTC</p><button className="quiet"><RefreshCw size={14}/> Refresh evidence</button></div>
    </aside>
    <main>
      <header><button className="menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="status-line"><Badge>DEMO</Badge><Badge tone="muted">REPLAY DATA</Badge><Badge tone="green">SIMULATED EXECUTION</Badge></div><div className="system-state"><span className={kill?"kill on":"kill"}><Power size={14}/>{kill?"Kill switch on":"Safety online"}</span><time>Updated just now</time></div></header>
      {error&&<div className="error" role="alert"><OctagonAlert size={18}/><span>{error}</span><button onClick={()=>setError("")}><X size={16}/></button></div>}
      <div className="workspace">
        {activePanel==="overview"&&<>
          <section className="overview-head"><div><h1>Exposure command</h1><p>Keep your BNB. Temporarily reduce its sensitivity to a decline.</p></div><button className="primary" onClick={()=>setNav("Create hedge")}><ShieldCheck size={17}/> Create hedge</button></section>
          <section className="exposure-stage">
            <div className="big-number"><span>Net exposure</span><strong>{net.toFixed(3)}</strong><em>BNB</em><p>{hedge?`${hedge.toFixed(0)}% protected by simulated short`:"Unhedged sample portfolio"}</p></div>
            <div className="exposure-rail" aria-label={`Net exposure ${net} BNB`}><div className="rail-labels"><span>0 BNB</span><span>5 BNB</span><span>10 BNB</span></div><div className="rail-track"><div className="protected" style={{width:`${100-net*10}%`}}/><div className="exposed" style={{width:`${net*10}%`}}/><i style={{left:`${net*10}%`}}/></div><div className="rail-legend"><span><b className="gold-dot"/>Simulated short {position?.state==="open"?position.remaining_quantity:"0.000"} BNB</span><span><b/>Remaining exposure {net.toFixed(3)} BNB</span></div></div>
            <div className="market-strip"><div><span>BNB spot</span><strong>$612.40</strong><small>Replay · 12:00 UTC</small></div><div><span>BNB perpetual</span><strong>$611.90</strong><small>Replay · 12:00 UTC</small></div><div><span>Funding / 8h</span><strong>0.0100%</strong><small>Projected, not charged</small></div><div><span>Active hedge</span><strong>{position?.state==="open"?"Monitoring":"None"}</strong><small>{position?.state==="open"?`${position.remaining_quantity} BNB short`:"Ready to plan"}</small></div></div>
          </section>
          <section className="lower-grid"><div className="scenario-block"><div className="section-title"><div><h2>Judge demo scenarios</h2><p>Load a complete safety state with one click.</p></div><Badge tone="muted">10 FIXTURES</Badge></div><div className="scenario-list">{scenarios.slice(0,5).map(s=><button key={s.id} onClick={()=>loadScenario(s.id)}><span className={s.outcome==="approved"?"scenario-icon good":"scenario-icon bad"}>{s.outcome==="approved"?<Check/>:<CircleStop/>}</span><span><strong>{s.label}</strong><small>{s.outcome==="approved"?"Safe path":"Policy rejection"}</small></span><ChevronRight/></button>)}</div></div><div className="activity-block"><div className="section-title"><div><h2>Evidence ledger</h2><p>Every decision remains attributable.</p></div></div><div className="ledger"><div><span className="ledger-mark">01</span><p><strong>Portfolio snapshot loaded</strong><small>10.000 BNB · demo fixture</small></p><time>now</time></div><div><span className="ledger-mark">02</span><p><strong>Market evidence verified</strong><small>Replay source · fixture digest stored</small></p><time>now</time></div>{receipts[0]&&<div><span className="ledger-mark active">03</span><p><strong>Receipt sealed</strong><small>{receipts[0].digest.slice(0,18)}…</small></p><time>now</time></div>}</div></div></section>
        </>}
        {activePanel==="create"&&<section className="create-layout"><div className="build-pane"><div className="section-title"><div><h1>Create a bounded hedge</h1><p>Describe the protection you want. Deterministic policy controls the result.</p></div><Badge>PLAN TTL · 5 MIN</Badge></div><label className="command-label">Protection instruction<textarea value={command} onChange={e=>setCommand(e.target.value)} rows={3}/><span><Sparkles size={14}/> Narrow deterministic interpreter · no paid LLM required</span></label><div className="control-row"><fieldset><legend>Hedge ratio</legend><div className="segment">{[25,50,100].map(n=><button className={ratio===n?"selected":""} onClick={()=>setRatio(n)} key={n}>{n}%</button>)}</div></fieldset><fieldset><legend>Duration</legend><select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="4">4 hours</option><option value="12">12 hours</option><option value="24">24 hours</option><option value="168">7 days</option></select></fieldset><fieldset><legend>Leverage</legend><select value={leverage} onChange={e=>setLeverage(Number(e.target.value))}><option value="1">1×</option><option value="2">2× max</option><option value="10">10× blocked</option></select></fieldset></div><button className="primary wide" disabled={!!busy} onClick={propose}>{busy||"Calculate & risk-check"}<ChevronRight size={17}/></button>
          <div className="all-scenarios"><span>Or load a judge scenario</span>{scenarios.map(s=><button key={s.id} onClick={()=>loadScenario(s.id)}>{s.label}</button>)}</div></div>
          <div className="proposal-pane">{!plan?<div className="empty-proposal"><Gauge/><h2>Your exact plan appears here</h2><p>Quantity, margin, costs, source evidence, and all ordered policy checks will be visible before confirmation.</p></div>:<><div className="proposal-top"><div><span>Proposed adjustment</span><strong>{proposal?.required_adjustment} BNB</strong><p>BNBUSDT perpetual · simulated short</p></div><Badge tone={approved?"green":"red"}>{approved?"RISK APPROVED":"RISK BLOCKED"}</Badge></div><div className="before-after"><div><span>Before</span><strong>{proposal?.net_exposure_before} BNB</strong><i style={{width:"100%"}}/></div><ChevronRight/><div><span>After</span><strong>{proposal?.net_exposure_after} BNB</strong><i style={{width:`${Number(proposal?.net_exposure_after)*10}%`}}/></div></div><div className="metrics"><div><span>Notional</span><strong>{money(proposal?.hedge_notional)}</strong></div><div><span>Margin at {leverage}×</span><strong>{money(proposal?.estimated_margin)}</strong></div><div><span>Total est. cost</span><strong>{money(proposal?.total_estimated_cost)}</strong></div><div><span>Reference</span><strong>{money(proposal?.reference_price)}</strong></div></div><div className="checks"><h3>Deterministic risk gate</h3>{plan.risk.checks.map((c:Any)=><div className={c.status} key={c.code}>{c.status==="pass"?<Check/>:<X/>}<span><strong>{c.code.replaceAll("_"," ")}</strong>{c.status==="block"&&<small>{c.explanation}</small>}</span></div>)}</div><div className="plan-id"><LockKeyhole size={15}/><span>Exact plan</span><code>{plan.plan_id}</code></div>{approved&&plan.state==="proposed"&&<button className="confirm" onClick={confirm} disabled={!!busy}>Confirm this exact plan</button>}{plan.state==="confirmed"&&<button className="primary wide" onClick={simulate} disabled={!!busy}>{busy||"Simulate hedge execution"}<ChevronRight/></button>}{plan.state==="completed"&&<div className="success"><Check/> Simulated hedge recorded. Receipt sealed.</div>}</>}</div></section>}
        {activePanel==="monitor"&&<section className="single-pane"><div className="section-title"><div><h1>Hedge monitor</h1><p>Position values are simulated. Market values use replay evidence.</p></div><Badge tone={position?.state==="open"?"green":"muted"}>{position?.state==="open"?"MONITORING":"NO ACTIVE HEDGE"}</Badge></div>{position?.state==="open"?<><div className="monitor-hero"><div><span>Effective hedge</span><strong>{position.hedge_ratio}%</strong><p>{position.remaining_quantity} BNB simulated short</p></div><div className="monitor-grid"><div><span>Entry price</span><strong>{money(position.entry_price)}</strong></div><div><span>Reference price</span><strong>{money(position.mark_price)}</strong></div><div><span>Simulated PnL</span><strong>{money(position.simulated_pnl)}</strong></div><div><span>Net exposure</span><strong>{net.toFixed(3)} BNB</strong></div><div><span>Funding estimate</span><strong>{money(plan?.proposal?.projected_funding||0)}</strong></div><div><span>Expiry</span><strong>{new Date(position.expires_at).toLocaleString()}</strong></div></div></div><div className="unwind"><div><ArrowDownToLine/><span><strong>Close the protection when you are ready</strong><small>A reduce-only unwind can close no more than {position.remaining_quantity} BNB.</small></span></div><button className="danger" onClick={unwind} disabled={!!busy}>{busy||"Prepare & simulate unwind"}</button></div></>:<div className="empty-proposal"><Radar/><h2>No open simulated position</h2><p>Create and confirm a hedge to begin monitoring.</p><button className="primary" onClick={()=>setNav("Create hedge")}>Create hedge</button></div>}</section>}
        {activePanel==="receipts"&&<section className="single-pane"><div className="section-title"><div><h1>Evidence receipts</h1><p>Canonical JSON, linked lifecycle events, and verifiable SHA-256 digests.</p></div><Badge tone="muted">{receipts.length} SEALED</Badge></div><div className="receipt-list">{receipts.map(r=><details key={r.receipt_id}><summary><FileCheck2/><span><strong>{r.kind==="opening"?"Hedge opened":"Hedge unwound"}</strong><small>{r.receipt_id}</small></span><Badge tone="green">DIGEST VERIFIED</Badge><time>{new Date(r.created_at).toLocaleString()}</time></summary><div className="receipt-body"><div className="digest"><code>{r.digest}</code><button onClick={()=>navigator.clipboard.writeText(r.digest)}><Copy size={15}/>Copy digest</button></div><pre>{JSON.stringify(r,null,2)}</pre><button onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:"application/json"}));a.download=`${r.receipt_id}.json`;a.click()}}><ArrowDownToLine size={15}/> Download JSON</button></div></details>)}{!receipts.length&&<div className="empty-proposal"><ReceiptText/><h2>No receipts yet</h2><p>Complete the canonical hedge flow to create the first tamper-evident record.</p></div>}</div></section>}
        {activePanel==="activity"&&<section className="single-pane"><div className="section-title"><div><h1>Activity</h1><p>Inspectable simulated lifecycle events.</p></div></div><div className="timeline">{["Replay market evidence loaded","Sample portfolio normalized","Safety policy initialized",...(receipts.length?["Simulated execution completed","Receipt digest verified"]:[])].map((x,i)=><div key={x}><span>{i+1}</span><p><strong>{x}</strong><small>Demo · simulated where financial · {new Date().toLocaleTimeString()}</small></p></div>)}</div></section>}
        {activePanel==="settings"&&<section className="single-pane"><div className="section-title"><div><h1>Safety settings</h1><p>Persisted controls for the no-funds demonstration.</p></div></div><div className="setting-row"><div><Power/><span><strong>Kill switch</strong><small>Blocks every new hedge proposal while enabled.</small></span></div><button className={kill?"danger":"secondary"} onClick={toggleKill}>{kill?"Disable kill switch":"Enable kill switch"}</button></div><div className="setting-row disabled"><div><LockKeyhole/><span><strong>Live execution</strong><small>No real-money path exists in this submission.</small></span></div><button disabled>LIVE — NOT AVAILABLE</button></div></section>}
      </div>
    </main>{mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
  </div>
}
